using GLTF
using Base.Test


function GLTFtest(file::AbstractString)
    rootDict = JSON.parsefile(file)
    println("load rootDict successfully.")
    GLTF.loadanimationsampler("samplerid", "animationid", rootDict)
    println("loadanimationsampler() checked.")
    GLTF.loadanimationchannels("animationid", rootDict)
    println("loadanimationchannels() checked.")
    GLTF.loadanimation("animationid", rootDict)
    println("loadanimation() checked.")
    GLTF.loadanimations(rootDict)
    println("loadanimations() checked.")
    GLTF.loadprofile(rootDict)
    println("loadprofile() checked.")
    GLTF.loadasset(rootDict)
    println("loaddasset() checked.")
    GLTF.loadbuffer("buffer_sphere", rootDict)
    println("loadbuffer() checked.")
    GLTF.loadcameraorthograhic("orthographicCamera_id", rootDict)
    println("loadcameraorthograhic() checked")
    GLTF.loadcameraperspective("perspectiveCamera_id", rootDict)
    println("loadcameraperspective() checked")
    GLTF.loadcamera("perspectiveCamera_id", rootDict)
    println("loadcamera() checked.")
    GLTF.loadcameras(rootDict)
    println("loadcameras() checked.")
    GLTF.loadbuffers(rootDict)
    println("loadbuffers() checked.")
    GLTF.loadbufferview("bufferView_vertex", rootDict)
    println("loadbufferview() checked.")
    GLTF.loadbufferviews(rootDict)
    println("loadbufferviews() checked.")
    GLTF.loadaccessor("accessor_position", rootDict)
    println("loadaccessor() checked.")
    GLTF.loadaccessors(rootDict)
    println("loadaccessors() checked")
    GLTF.loadshader("vertexShader0", rootDict)
    println("loadshader() checked.")
    GLTF.loadshaders(rootDict)
    println("loadshaders() checked.")
    GLTF.loadprogram("program0", rootDict)
    println("loadprogram() checked.")
    GLTF.loadprograms(rootDict)
    println("loadprograms() checked.")
    GLTF.loadtechniqueparameter("modelViewMatrix", "technique0", rootDict)
    println("loadtechniqueparameter() checked.")
    GLTF.loadtechniqueparameters("technique0", rootDict)
    println("loadtechniqueparameters() checked.")
    GLTF.loadtechniquestates("technique0", rootDict)
    println("loadtechniquestates() checked.")
    GLTF.loadtechnique("technique0", rootDict)
    println("loadtechnique() checked.")
    GLTF.loadtechniques(rootDict)
    println("loadtechniques() checked.")
    GLTF.loadmaterial("material_czmDefaultMat", rootDict)
    println("loadmaterial() checked.")
    GLTF.loadmaterials(rootDict)
    println("loadmaterials() checked.")
    GLTF.loadmeshprimitives("mesh_sphere", rootDict)
    println("loadmeshprimitives() checked.")
    GLTF.loadmesh("mesh_sphere", rootDict)
    println("loadmesh() checked.")
    GLTF.loadmeshes(rootDict)
    println("loadmeshes() checked.")
    GLTF.loadskin("skin_id", rootDict)
    println("loadskin() checked.")
    GLTF.loadskins(rootDict)
    println("loadskins() checked.")
    return true
end

@test GLTFtest("sphere.gltf")
